### ISSUE TITLE
Public display of suppressed guides not working correctly

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#1001]
a) it is not checking to see if it should do a header override.  This should be fixable in the checkVisibility() function in the Guide class.  But then there is b) where, at least at UM, on our production server the authenticated user can't see a public view of a suppressed guide.  In theory, if you are logged in, you should be able to see these, but the Session variables don't seem to be accessible.  They are on our localhosts and development server.

**Comment by pvillanueva01** [comment]
Fixed in #837
