### ISSUE TITLE
Problems with Database by Subject Associations

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#1058]
The new DB by Subjects tool is awesome, but it seems that a) one can no longer set A-Z list subjects via the dropdown on the Record editing screen, and b) when you change something in the Record screen, it wipes out the association(s) set via the DB by Subjects tool.

**Comment by abelfacenda** [comment]
[23dc9fc] Bug fixed. Added dbbysub_active to Record class so the association can be properly handled
