### ISSUE TITLE
Sql injection vulnerability on all versions!

### ISSUE THREAD

**Issue by t4lha** [subjectsplus/SubjectsPlus#1198]
I found sql injection vulnerabilities on all  versions SubjectPlus ( I tested on 4.2 and 3 ) Can you contact with me talha.gunay@gmail.com

**Comment by abelfacenda** [comment]
Escaped user input and rewritten involved SQL query using parameterized queries

**Comment by attritionorg** [comment]
@abelfacenda, can you link to the fixing commit and confirm which version fixes this? Thanks!

**Comment by abelfacenda** [comment]
@attritionorg Please refer to this commit [https://github.com/subjectsplus/SubjectsPlus/commit/27e2f38d17b9f614d9b3299e45d78516d8ee39e5](url)
Version 4.2.2 fixes it.

**Comment by attritionorg** [comment]
@abelfacenda Thank you!
