### ISSUE TITLE
Linked List -- Not Showing all resources when box unticked

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#1213]
In theory, unticking the " Limit to AZ List" box should show all resources, but it has been reported by Diane that this is not the case.  Need to investigate.

**Comment by cgb37** [comment]
don't load the list until 3 characters have been entered into the input field after unclicking az list

**Comment by cgb37** [comment]
merged with #1106

**Comment by abelfacenda** [comment]
Fixed on [f8f4c21c27dba349b6072a683a55a3e70b40366f]

-Limited search results to 50.
-Search term has to be 3 characters minimum to initiate a search.
