### ISSUE TITLE
If Supervisor isn't chosen in Add User screen, the save will fail

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#1275]
Need to make sure the "external supervisor" option puts an entry into the database, and/or check db structure.

**Comment by Barulaganye-Hulela** [comment]
Thanks, i did exactly that,now my users are visible.

**Comment by abelfacenda** [comment]
[18cb1946913ad6b19f1a0f2c11661a4df5b0c719] 
-Made department a required field
-External supervisor value equals to -1
