### ISSUE TITLE
v4.2.2 is api working

### ISSUE THREAD

**Issue by rhoit** [subjectsplus/SubjectsPlus#1276]
my setup:
-   SubjectsPlus-4.2.2
-   php-fpm-5.6.35

for route `/api` things seems fine

![image](https://user-images.githubusercontent.com/1684754/39681883-7d425600-51cc-11e8-81bc-daa38d914990.png)

after that everthing is 404

![image](https://user-images.githubusercontent.com/1684754/39681923-a9011056-51cc-11e8-9f12-d5e07ab17490.png)

**Comment by abelfacenda** [comment]
Hello @rhoit,

Do you have mod_rewrite enabled?

**Comment by rhoit** [comment]
seems like mod_rewrite is the **apache** thing closest I could come up was in this [article](https://www.digitalocean.com/community/questions/enabling-nginx-mod_rewrite)

after adding `try_files $uri $uri/ /index.php?$args;` to my nginx config

now it seems to redirect to `subjects/index.php` after the api and shows "File not found."
that is when I tried
http://localhost:8080/api/staff/output/xml/key/ul8RJihecJq7K8IoKMkF its redirected to http://localhost:8080/api/staff/output/xml/key/subjects/index.php

![image](https://user-images.githubusercontent.com/1684754/39770337-65d41916-530e-11e8-850e-b3610d917e9d.png)

![image](https://user-images.githubusercontent.com/1684754/39770713-8465a830-530f-11e8-990e-4fbb3e9056d3.png)

here are the logs:

    web_1      | 172.20.0.1 - - [08/May/2018:16:37:58 +0000] "GET /api/staff/output/xml/key/ul8RJihecJq7K8IoKMkF HTTP/1.1" 302 2765 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "-"
    php-fpm_1  | 172.20.0.4 -  08/May/2018:16:37:58 +0000 "GET /api/staff/output/xml/key/subjects/index.php" 404
    php-fpm_1  | 172.20.0.4 -  08/May/2018:16:37:58 +0000 "GET /index.php" 302
    web_1      | 2018/05/08 16:37:58 [error] 8#8: *39 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: _, request: "GET /api/staff/output/xml/key/subjects/index.php HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost:8080"
    web_1      | 172.20.0.1 - - [08/May/2018:16:37:58 +0000] "GET /api/staff/output/xml/key/subjects/index.php HTTP/1.1" 404 27 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "-"


    web_1      | 172.20.0.1 - - [08/May/2018:16:45:57 +0000] "GET /api/database/letter/A/key/ul8RJihecJq7K8IoKMkF HTTP/1.1" 302 2765 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "-"
    php-fpm_1  | 172.20.0.4 -  08/May/2018:16:45:57 +0000 "GET /index.php" 302
    php-fpm_1  | 172.20.0.4 -  08/May/2018:16:45:57 +0000 "GET /api/database/letter/A/key/subjects/index.php" 404
    web_1      | 2018/05/08 16:45:57 [error] 8#8: *109 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: _, request: "GET /api/database/letter/A/key/subjects/index.php HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost:8080"

here is my full configurations, yes i'm testing in docker
https://gist.github.com/509ec261123a383fe1dc68957656d187

**Comment by rhoit** [comment]
my setup:
- PHP 7.1.17-1+ubuntu16.04.1+deb.sury.org+1 (cli)
- subjectsPlus 4.2.2
- apache Apache/2.4.18

I also tried it in **apache** but still having same problem, (not trying in docker)

    # sudo a2enmod rewrite
       Module rewrite already enabled

apache log shows

    127.0.0.1 - - [10/May/2018:11:00:53 +0545] "GET /sp/api/staff/email/test%40gmail.com/max/99/15pG6JH0yc71G2etSqaA HTTP/1.1" 404 520 "WordPress/4.9.5; http://localhost/wordpress"
    127.0.0.1 - - [10/May/2018:11:34:37 +0545] "GET /sp/api/staff/key/15pG6JH0yc71G2etSqaA HTTP/1.1" 404 526 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:59.0) Gecko/20100101 Firefox/59.0"

**Comment by rhoit** [comment]
finally got working on apache setup,  with apache config

    <Directory /var/www/html/sp>
        AllowOverride All
    </Directory>

now trying for **nginx**

**Comment by rhoit** [comment]
finally translated `api/.htaccess` to **nginx** config

![image](https://user-images.githubusercontent.com/1684754/39870758-31355fb0-5482-11e8-9f86-a96332702403.png)


adding the following rewrite rule in server block solved the problem.

    location / {      
        if (!-e $request_filename){
            rewrite ^.*$ /api/index.php?$args last;
        }
    }

here is my nginx config [sp.conf](https://github.com/subjectsplus/SubjectsPlus/files/1991674/sp.txt)

**Comment by agdarby** [comment]
Hi @rhoit -- just as an FYI, SubjectsPlus will have problems with v4.x if you run PHP7.  We recommend 5.3 - 5.6.  Thanks for the info for nginx users!
