### ISSUE TITLE
Update Catalog Search pluslet to use new Primo UI 

### ISSUE THREAD

**Issue by pvillanueva01** [subjectsplus/SubjectsPlus#1295]
Right now it seems to redirect, but this may break later

**Comment by pvillanueva01** [comment]
Tested on: /subjects/psych#tab-2

The values on the input are not passing through - still broken

**Comment by pvillanueva01** [comment]
Pluslet is using the correct values for primo but the javascript is not executing and passing values to the form = empty field = empty search results

**Comment by abelfacenda** [comment]
[53e7fa7da59c0bb39e1d6f4c8607aeb759a31c09] 
switched selectors to class instead of id
