### ISSUE TITLE
Update Articles+ Search pluslet to use new Primo UI 

### ISSUE THREAD

**Issue by pvillanueva01** [subjectsplus/SubjectsPlus#1296]
It should be labeled uSearch

Right now it redirects but may break later

**Comment by pvillanueva01** [comment]
Tested on: /subjects/psych#tab-4

values entered on search not passing through - broken

**Comment by pvillanueva01** [comment]
Pluslet is using the correct values for primo but the javascript is not executing and passing values to the form = empty field = empty search results

**Comment by abelfacenda** [comment]
[21111e62ba898362e41494ad1d78d79287c48b02]
changed jquery code to be class based instead of id based
