### ISSUE TITLE
Add default image to staff list so it's not a blank

### ISSUE THREAD

**Issue by pvillanueva01** [subjectsplus/SubjectsPlus#1299]

**Comment by isaboy** [comment]
Could you provide a link with a sample of what you mean?

**Comment by pvillanueva01** [comment]
Default staff image shows up on staff listing for "Departments" view but not on "Subject Librarians" view on UM new theme, see: staff.php?letter=Subject Librarians

**Comment by pvillanueva01** [comment]
Also need to fix these pages on the UM New theme

/subjects/staff.php?letter=Subject Librarians a-z

/subjects/staff.php?letter=By%20Department

right now we cannot see them because of the redirect
