### ISSUE TITLE
New Record for print books

### ISSUE THREAD

**Issue by zydlewsd** [subjectsplus/SubjectsPlus#1300]
When I change the format from "Web" to "Print" the the Location URL does not go away so there are text boxes to enter both a URL and the Call Number.  It displays the hyperlink and not the call number.  (For older records, prior to upgrading to 4.0, this has not been a problem.

**Comment by agdarby** [comment]
![image](https://user-images.githubusercontent.com/3627120/43150536-27452936-8f38-11e8-85c0-e6f6c9122378.png)

**Comment by agdarby** [comment]
I do believe I have fixed this!  There's still an issue with print books not actually showing db list with print text rather than the URL...
