### ISSUE TITLE
Special characters requirement in passwords

### ISSUE THREAD

**Issue by sandbergja** [subjectsplus/SubjectsPlus#1316]
From my reading of the code, staff passwords currently require at least one of the following characters: !@#$%^&*

That list is defined on this line: https://github.com/subjectsplus/SubjectsPlus/blob/master/lib/SubjectsPlus/Control/Staff.php#L1499

I can't find where that list of characters is given to the user.  I wonder if it might reduce user frustration to expand that list somewhat -- like adding some of ~`()+={}[]\|?/-_<>,. -- and/or letting users know what special characters are accepted?

**Comment by isaboy** [comment]
I don't see why not. Adding those characters would be good, but the password system does ask for a special character. Perhaps we could add a button that shows a textbox of what those characters are?

**Comment by agdarby** [comment]
I wonder about just requiring more characters, since nowadays people seem to recommend longer strings (usually phrases) rather than short messes of text/nums/special characters

**Comment by agdarby** [comment]
We've added in text that explains the requirements at the top of password reset screens.  So half addressed.  We might look at better password scheme in v5, but I'm going to close this puppy.
