### ISSUE TITLE
Override issues in Guide Collections admin panel

### ISSUE THREAD

**Issue by pvillanueva01** [subjectsplus/SubjectsPlus#1325]
When you edit a guide collection (adding guides), the collection metabox removes the shortform

If you edit a different collection, somehow your changes get applied to the collection you had previously edited, overriding all your work. 

Only works after editing a collection, saving it and refreshing the page

**Comment by abelfacenda** [comment]
[ec1b8759bff4205e507c80f2d78d7c3d530a2793] The click event in the edit collection metadata button was being added several times to the same button, causing the save function to be called for each edited collection id and always saving the information that was inserted last in the metadata fields.
