### ISSUE TITLE
Need to use different default image for users

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#1328]
Right now it's the U Miami U

![image](https://user-images.githubusercontent.com/3627120/51750178-3db94c00-207f-11e9-9d6a-c9256d45eaa4.png)

**Comment by pvillanueva01** [comment]
Fix for headshot default images and related uses:
- Added placeholder images
- Added fix to control/user.php to use placeholder image before a user is created (empty form)
- Updated configs to enable institution code for customizations. Conditional for headshot image for UM and non-UM institutions. 
- Fixed issue with getting large or mini version of image to prevent pixelation/lossiness

![screen shot 2019-02-06 at 12 52 19 pm](https://user-images.githubusercontent.com/8170097/52363237-43644980-2a10-11e9-862f-0e2ce6da283c.png)
