### ISSUE TITLE
Get rid of old icons in default SP theme

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#1335]
Move to font awesome?  Also, remove the heart from default one.

![image](https://user-images.githubusercontent.com/3627120/52289018-3e819600-293b-11e9-94ee-844a93ab5703.png)

**Comment by pvillanueva01** [comment]
Updated old image icons with font-awesome icons, including markup for version 4 and 5 to support legacy themes. Removed favorite links/heart from default theme.
