### ISSUE TITLE
Add "and more" to experts on U Miami theme

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#1337]
![image](https://user-images.githubusercontent.com/3627120/52298197-72b38180-2950-11e9-8dfd-9f088b710805.png)

The way it is now leads one to believe that that is their only subject-- <link to profile>and more</link> would make it clearer that's just one

**Comment by pvillanueva01** [comment]
Added "and more" with link to staff profile for staff listed on guide index page only for UM New Theme
