### ISSUE TITLE
Migrate Staff Map View and 'Get Coordinates' Button from Google Maps to Mapbox

### ISSUE THREAD

**Issue by alirsattar** [subjectsplus/SubjectsPlus#1376]
### What's Wrong?
- The Google Maps SDK and API now requires a credit card be provided even to use free tier services, and so the decision was made to research alternatives.
- Google Maps based mapping features -- geocoding (converting physical street addresses to coordinates for purposes of mapping staff members, and Google Maps generation with staff members as location pins -- were broken or otherwise not in a production-ready state.

### Solution
- The Mapbox Geocoding API (https://docs.mapbox.com/api/search/#forward-geocoding) and Mapbox GL JS (SDK) were selected as the alternative of choice.
- All previous Google Maps features were recreated using Mapbox

### Test Cases
Given | When | Then | Passed?
------------ | ------------- | ------------- | -------------
**Coordinate Lookup Button**
User with __**VALID**__ street address info | "Look Up Now" button underneath street address info box is clicked | Latitude/longitude text input box is populated with correct latitude and longitude for that street address | ✅
User with __**INVALID**__ street address info | "Look Up Now" button is pressed | User gets a popup 'alert' dialog saying coordinates could not be found, they should verify that address info is correct and record has been properly saved | ✅
**Staff_Map View Authorizations**
User __**WITH**__ “view_map” session flag (ie. flag is added/removed, user logs out, and site is hard reloaded) | Navigates to /control/admin/staff_map.php | User is able to view updated Mapbox map | ✅
User __**WITHOUT**__ “view_map” flag (ie. flag is added/removed, user logs out, and site is hard reloaded) | Navigates to /control/admin/staff_map.php | User is __**NOT**__ able to view updated Mapbox map, and is presented with “You are not authorized to view this.” message | ✅
**Mapbox Features**
User with __**VALID**__ coordinates | Staff_Map.php map is shown | User has a marker at correct latitude-longitude position | ✅
User with __**NO/INVALID**__ info | Staff_Map.php map is shown | User does not have a marker on the map, and other users’ markers are unaffected | ✅
Staff_Map.php view is shown | Staff member marker is clicked | Popup created inside of Mapbox map, displaying staff member info | ✅
Staff_Map.php view is shown | Marker is clicked for staff member __**WITH NO**__ missing info, and popup appears | All fields in popup (headshot, full name, position, full address, email, home phone, cell phone, emergency contact name/relationship/phone number) are populated | ✅
Staff_Map.php view is shown | Marker is clicked for staff member __**WITH**__ missing info, and popup appears | Missing info fields are replaced with “Not on File” | ✅

**Comment by alirsattar** [comment]
This issue is tied to branch 'ali-dev,' up to and including commit ID # ae79a48a20032e10e5225e80912a6fa5425c000b.

Link: https://github.com/subjectsplus/SubjectsPlus/commit/ae79a48a20032e10e5225e80912a6fa5425c000b

**Comment by cgb37** [comment]
Done
