### ISSUE TITLE
HTMLPurifier needs to be updated to be compatible with PHP 7.2

### ISSUE THREAD

**Issue by sandbergja** [subjectsplus/SubjectsPlus#1384]
On PHP 7.2 and above, this deprecation warning starts showing up:

`Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in /home/site/wwwroot/lib/HTMLPurifier/HTMLPurifier.autoload.php on line 17`

HTMLPurifier does have an up-to-date version (4.12.0) that is compatible with PHP 5.3-7.4.  Maybe we should move to that to avoid those deprecation warnings.

This is related to #1320.

**Comment by candise** [comment]
Has any work been done on this? I'm getting this issue after upgrading to v4.4.

**Comment by abelfacenda** [comment]
HTMLPurifier updated to version 4.12.0 [516f0485b610369185a63849d6cdfc9c1528f53f]
