### ISSUE TITLE
Link List pluslet can get cut off on smaller screens

### ISSUE THREAD

**Issue by sandbergja** [subjectsplus/SubjectsPlus#1392]
Here is a screenshot from one of our librarians, who was unable to add a description when adding a new record to a link list on a laptop:

![image(1)](https://user-images.githubusercontent.com/7086943/79292182-5892fe80-7e85-11ea-829d-6a9642a96e0f.png)

There is a scrollbar in the modal, but it is greyed out so the user can't actually scroll down.

**Comment by alirsattar** [comment]
[e48f0af] adds a simple CSS rule in admin_styles.css to address the modal not scrolling on low-resolution or high scaling displays.

Created PR #1403
