### ISSUE TITLE
Video thumbnails are required to have .jpg extension

### ISSUE THREAD

**Issue by sandbergja** [subjectsplus/SubjectsPlus#1393]
Steps to reproduce:

1. Log in to the staff side of SubjectsPlus
2. If you don't already have some videos, add one.
3. Go to Videos > List Current
4. Click the Pencil icon for one of the videos.
5. Click to update thumbnail.
6. Add a PNG image.
7. Navigate to the public view of the videos page.  Note that your video shows the default thumbnail instead of your great PNG thumbnail.
8. Repeat steps 1-6 with a JPG image.  Note that the video shows the thumbnail now.

**Comment by abelfacenda** [comment]
Added accept="image/jpeg" to upload box of Videos. This should limit the upload options to only jpeg images  [166477fdbcc463abe1c20dee399757df5e8be251]
