### ISSUE TITLE
Allow Multiple Words in Guide Types

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#1399]
see:  https://groups.google.com/forum/#!topic/subjectsplus/dYBtkqd5M1w

**Comment by abelfacenda** [comment]
This was a issue specific for the UML theme. 
Solved by replacing spaces in affected id attributes with dashes.
[4cc2e4886c54f44e8dd61a1f59c745d0ccc03a0a] on theme repository.
