### ISSUE TITLE
Guide Collections "Are You Sure?"

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#1400]
When you try to delete an existing guide, you get an "Are you Sure?" alert popup, but there is an "okay" and no cancel button.  So you have to refresh the page if you realize you didn't want to actually delete the guide collection.

**Comment by abelfacenda** [comment]
[d0481d531de5c9137369300d365f6b759b87b84f] Switched to confirm dialog instead of alert dialog.
