### ISSUE TITLE
It's easy to lose work in guides

### ISSUE THREAD

**Issue by sandbergja** [subjectsplus/SubjectsPlus#1404]
I am not quite sure how this happens, but it's not uncommon for our librarians to lose their work when editing text boxes in guides.  If I happen to have an old copy of the database, I can sometimes recover their content, but it's not guaranteed.

Any ideas on how to mitigate this?

**Comment by agdarby** [comment]
We encounter this, too.  The two suggestions we make are to not leave things open when you go for lunch--we use single sign-on, and it bumps people out after x minutes--and save often.  Also, don't edit simultaneously with a colleague.  But at the bottom, there is a LOT of JS happening, and it can be hard to pin down exactly why something happened when in what browser/OS.

**Comment by cgb37** [comment]
too vague
