### ISSUE TITLE
Have feedback when adding a guide to a collection

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#1414]
In Admin > Guide Collections, it's unclear when you have saved a new guide collection that the save has taken place, since there is no "save" button like elsewhere in the application.  Need to add the little alert bar on top each time a new guide has been added to the collection

**Comment by abidfakhrealam** [comment]
I think in http://localhost/sp/control/admin/guide_collections.php page somethink is missing but when  http://localhost/sp/control/admin/guide_collections-org.php page it allow me to add the guide.
