### ISSUE TITLE
In the search, include search term in search box

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#1446]
I.e., here:

![image](https://user-images.githubusercontent.com/3627120/93380206-edcb6200-f82c-11ea-8372-7a37caefbc46.png)

Otherwise, you have to retype each time if you need to run the search repeatedly. (Say you are fixing something sitewide.)

**Comment by rxd702** [comment]
Issue has been fixed in https://github.com/subjectsplus/SubjectsPlus/pull/1489.
