### ISSUE TITLE
Splash page (+ first install modal) not showing up

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#1455]
Error is in functions.php's SeeRecentChanges (line 713).  The query conks out with an error of

Error Code: 1055. Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'subjectsplus5_dev_db.chchchanges.record_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

I think the solution has to do with a MySQL setting, see here:

https://stackoverflow.com/questions/37951742/1055-expression-of-select-list-is-not-in-group-by-clause-and-contains-nonaggr

**Comment by cgb37** [comment]
fixed - see [#1461] merged and deployed
