### ISSUE TITLE
Domain subjectsplus.com in repo "About" is dead

### ISSUE THREAD

**Issue by onshisan** [subjectsplus/SubjectsPlus#1552]
The domain [subjetsplus.com](https://www.subjectsplus.com) appears to be dead. It's included in this repo's "About" info:

![image](https://github.com/subjectsplus/SubjectsPlus/assets/7659358/98cd39c4-e4d2-46c8-8b7e-88542888f4b5)

Likewise, in README.md:
https://github.com/subjectsplus/SubjectsPlus/blob/56d768f1670f32944ca8b6d22a8133c7fe85deba/README.md?plain=1#L17

If this domain is no longer in use, perhaps this should be changed.

**Comment by agdarby** [comment]
Thanks for pointing this out.  I've updated the About to point to SP's new brochure site:  https://subjectsplus.github.io/
