### ISSUE TITLE
Missing home tab icon in UM theme

### ISSUE THREAD

**Issue by little9** [subjectsplus/SubjectsPlus#190]
![screen shot 2015-09-22 at 12 00 20 pm](https://cloud.githubusercontent.com/assets/4324761/10024414/20bc05ba-6125-11e5-8e27-ab6798b72420.png)

What should happen if this tab has a different name?

**Comment by agdarby** [comment]
It should show that name

**Comment by pvillanueva01** [comment]
This was fixed by CBR. PV applied styling on UM and default themes.
