### ISSUE TITLE
Deleting a guide just brings up an empty page 

### ISSUE THREAD

**Issue by pvillanueva01** [subjectsplus/SubjectsPlus#191]
Delete --> Are you sure? --> Empty page

the URL reads as follows:

/control/guides/metadata.php?subject_id=133&delete_record=true&wintype=pop

**Comment by little9** [comment]
On my install there is some text at the top of the window that says "Thy will be done. Offending Guide (and associated boxes) deleted. Close window to continue." Should this just redirect users back the guide selection page? 

![screen shot 2015-10-01 at 1 16 44 pm](https://cloud.githubusercontent.com/assets/4324761/10227977/83c1d1e2-683e-11e5-8e3c-1a541b0ef8a3.png)

**Comment by pvillanueva01** [comment]
Fix for missing message upon deleting guide. Added link to "Browse Guides" page.
