### ISSUE TITLE
Guide flyout covers leftmost column

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#241]
Is it possible to make the drop areas flush(er) right?

**Comment by pvillanueva01** [comment]
We can change the flyout to "push the content" rather than "cover/overlay" the content...how do we address the scrollbars to get to the right column?

**Comment by little9** [comment]
You could do #tabs { margin-left: 32%; } and have the flyout always visible. 
![screen shot 2015-10-20 at 3 57 20 pm](https://cloud.githubusercontent.com/assets/4324761/10619335/1d18c446-7743-11e5-8962-b0ba2e459f40.png)
