### ISSUE TITLE
If no subject specialist set, say something in the SubSpecialist pluslet

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#245]

**Comment by agdarby** [comment]
I think this is actually back end; maybe the front end should not show the pluslet if no one is set :)

**Comment by little9** [comment]
This only happens with the importer..

**Comment by cgb37** [comment]
added conditional to check to see if a user is associated with a guide before subject specialist pluslet will display options. Rarely happens, only on import of lib guides does it seem to appear.
