### ISSUE TITLE
Create a width constraint variable to be used by containers on front and back ends

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#297]
I.e., to set both to 1024px or whatever, so there isn't a discrepancy between what you build with on the back, and what you see on the front

**Comment by cgb37** [comment]
added $guide_container_width as a config variable that is set in Admin Config site. It controls the max width of the admin guide view. [696135d]

** only works on admin view - because of themes variation set admin config to match end user view
