### ISSUE TITLE
box-undefined

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#303]
I'm still getting this message sometimes when I click onto a tab of a guide.  e.g.,

http://subjectsplus.com/manual/subjects/guide.php?subject=admin#box-undefined

**Comment by agdarby** [comment]
Is this fixed?  If you go here:

http://subjectsplus.com/manual/subjects/guide.php?subject=admin

and click on the second tab, you get that box undefined.  This is with the
latest commits.

**Comment by little9** [comment]
![screen shot 2015-11-10 at 1 36 04 pm](https://cloud.githubusercontent.com/assets/4324761/11071612/a4c9db92-87af-11e5-8625-2daa1516376e.png)
![screen shot 2015-11-10 at 1 36 12 pm](https://cloud.githubusercontent.com/assets/4324761/11071620/a9ecc508-87af-11e5-8875-17af6fc53911.png)

It should look like that...

**Comment by agdarby** [comment]
Okay, working now, thanks!
