### ISSUE TITLE
On edit-config page, we've got an undefined index

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#350]
Notice: Undefined index: guide_container_width in C:\wamp\www\sp4qa\lib\SubjectsPlus\Control\Config.php on line 411

**Comment by little9** [comment]
Charles added this to the edit-config file and the config-default, so the variable is created in a new install, but if you have an earlier config file this variable won't be declared. Putting 

```php
$guide_container_width = array( "1260px");
```
in the config.php file will resolve this.
