### ISSUE TITLE
Search box on index.php returns a blank page with empty serach

### ISSUE THREAD

**Issue by pvillanueva01** [subjectsplus/SubjectsPlus#362]
Index needs to redirect to itself instead of 
http://sp4.library.miami.edu/subjects/search_results.php

See databases.php for example

**Comment by pvillanueva01** [comment]
This also happens when the search box is on sidebar -- see collections.php

http://sp.library.miami.edu/subjects/collection.php

**Comment by agdarby** [comment]
Andrew the hero has finally fixed this one, at least for the UM theme
