### ISSUE TITLE
kaltura video and rss content don't display on guide page (admin side)

### ISSUE THREAD

**Issue by pvillanueva01** [subjectsplus/SubjectsPlus#375]
but they DO display on the public guide page
![screen shot 2015-12-03 at 12 54 19 pm](https://cloud.githubusercontent.com/assets/8170097/11568974/2f14a84e-99bd-11e5-9f45-6df26afff92c.png)
![screen shot 2015-12-03 at 12 54 30 pm](https://cloud.githubusercontent.com/assets/8170097/11568985/36f62aba-99bd-11e5-82fc-be68749ff054.png)

**Comment by little9** [comment]
The RSS is not working on the back end because we use https for the /control part of the site and then not at all for the public site. The script that gets RSS data is in /subjects. I switched a Kaltura CDN that is compatible with https to fix the Kaltura issue.
