### ISSUE TITLE
Default images

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#390]
Need a better default person image (i.e., not the butterfly), also there's a new $collection_thumbnail_default in the config that needs to point to something other than our chc thumbnail

**Comment by pvillanueva01** [comment]
Added books image as default for collection_thumbnail_default

**Comment by pvillanueva01** [comment]
Added 2 new default images for headshot and headshot 2
![headshot2](https://cloud.githubusercontent.com/assets/8170097/12791168/c3005ac6-ca73-11e5-9f54-8874160e580a.jpg)
![headshot](https://cloud.githubusercontent.com/assets/8170097/12791167/c2f4e2e0-ca73-11e5-9926-db61dcdd55b2.jpg)
