### ISSUE TITLE
Titlebar Styles on Config get overwritten when the edit-config.php gets updated

### ISSUE THREAD

**Issue by pvillanueva01** [subjectsplus/SubjectsPlus#404]
... and results in a 0/1 as the values of the dropdown instead of the declared values

![screen shot 2016-01-08 at 1 23 31 pm](https://cloud.githubusercontent.com/assets/8170097/12205843/7c02cc70-b60b-11e5-8610-346ad60f470b.png)

It is entered as follows on the config.php and config-default.php

$titlebar_styles = array( "Regular Heading" => "ts-umcream", "Alternative Heading" =>"ts-umgreen");
 

We need a way to enter this array into the edit-config.php

**Comment by cgb37** [comment]
Fixed - [9a80db7] option in select dropdown set to $key and it should be $value
