### ISSUE TITLE
Deleting multiple pluslets creates ui-overlay issue

### ISSUE THREAD

**Issue by pvillanueva01** [subjectsplus/SubjectsPlus#405]
When deleting more than 2 pluslets on a guide, the third time creates an overlay issue and the pop up box cannot be accessed

**Comment by pvillanueva01** [comment]
This continues to happen - have to find a way for ui-overlay to stop increasing z-index value with every call so that it won't conflict with ui-dialog box z-index

**Comment by cgb37** [comment]
Fixed #405 [6fc00a6] set modal property of dialog to false. setting it true was causing an overlay issue rendering dialog boxes inaccessible after three pluslet deletes.
