### ISSUE TITLE
Links Pluslet

### ISSUE THREAD

**Issue by pvillanueva01** [subjectsplus/SubjectsPlus#416]
Create new "Links" pluslet where user enters a title and a URL - instead of using CK Editor link functionality which seems "intimidating" - need to able to add multiple links

**Comment by agdarby** [comment]
C'mon, just learn how to do stuff.  Charles will look for ckeditor plugin.  But that's it.

**Comment by agdarby** [comment]
I think we did this with LinkList pluslet
