### ISSUE TITLE
LibGuides > SP Migrator -- check initial article munging

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#424]
i.e., moving article into prefix field sometimes not quite working right, either cutting off the letter A unnecessarily (leading to "-Z list of Something") or treating "an" as "a" (leading to "n Dictionary of Something")

**Comment by little9** [comment]
I changed the regex to have a space after the article. 

The Cat in the Hat will show up as Cat in the Hat, but A-Z will not get split up 

These are the articles I'm removing:
\b(the |a |an |la |les |el |las |los )\b/i
