### ISSUE TITLE
If you navigate to sp/subjects/ before install, you see a mess

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#438]
We should do something about that.
![sp-not-yet-installed](https://cloud.githubusercontent.com/assets/3627120/13297506/bb8a19f6-db00-11e5-887e-5ac10bc989d7.png)

**Comment by little9** [comment]
Add a check for db connection and add click here to install if not

**Comment by cgb37** [comment]
Fixed
