### ISSUE TITLE
ChunkFiveRegular is a non UTF-8 font

### ISSUE THREAD

**Issue by mitjaiskric** [subjectsplus/SubjectsPlus#46]
Special characters in translations looks bad when using special UTF-8 characters
![chunkfive](https://cloud.githubusercontent.com/assets/6222426/7135912/b9043e1c-e2ab-11e4-9c7e-88dca2f84d59.png)

**Comment by agdarby** [comment]
for v4, we've switched to NotoSansBold--hopefully this will work better with UTF-8.  https://www.google.com/fonts/specimen/Noto+Sans
