### ISSUE TITLE
New guides should have the UM header type 

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#495]
![header_type](https://cloud.githubusercontent.com/assets/3627120/14989169/927153b8-1124-11e6-8d07-5a53c26a8d3b.png)

You have to re-save the metadata for it to have the um header.  Maybe this isn't a big deal.  Maybe its not an importer issue.

**Comment by little9** [comment]
This is being set in the database as 'um' now, but the control doesn't seem to reflect what's in the database.
