### ISSUE TITLE
When we display a file, we should show an icon

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#513]
e.g., markup is like this:

<div class="file">
<div class="file-title"><a href="http://libguides.miami.edu/loader.php?type=d&amp;id=1289630">The Clinical Question and Useful Calder Library Resources</a></div>

<div class="file-description">&nbsp;</div>
</div>

**Comment by little9** [comment]
I don't have a way of knowing what file type the link is. 

Do you want to the generic Font Awesome file icon?

**Comment by agdarby** [comment]
Hmm, ok.  This will show us where files are that need to be re-linked, if nothing else.
