### ISSUE TITLE
Last Modified date in  "Edit Existing Metadata" window being pulled for records.  

### ISSUE THREAD

**Issue by louisachoy** [subjectsplus/SubjectsPlus#570]
The Last Modified date in the "Edit Existing Metadata" window for the guides is pulling the most recent dates for the records instead of the guides.  For example, instead of pulling the last modified date for a guide with id=19, it is pulling the last modified date for a record with id=19.  You can fix this by going to SubjectsPlus\Control\Guide.php and around line 388, swap out "record" for "guide".

**Comment by agdarby** [comment]
Thanks, Louisa, fixed in master.
