### ISSUE TITLE
Links to guides under Subject Area menu on staff_details are incorrect

### ISSUE THREAD

**Issue by cgb37** [subjectsplus/SubjectsPlus#710]
See commit [56c4e3d] for temporary fix in place
This is a temporary fix to make the links work until we can determine why $linky is creating bad links to guides. For example, http://sp.library.miami.edu/subjects/profile/govdocs and every other link like it point to Roca Beiro staff details page.
//hotfix-staff-link branch - 8-17-2016
        /*
         \* @TODO fix the path
         _/
        /_
        if ($mod_rewrite == 1) {
            $linky = $mysubs[2];
        } else {
            $linky = "guide.php?subject=" . $mysubs[2];
        }
        */
        $linky = "/subjects/guide.php?subject=" . $mysubs[2];
        //end hotfix

**Comment by agdarby** [comment]
the issue is it needs to strip off that profile directory when linking to guide

**Comment by abelfacenda** [comment]
Bug can't be replicated. Issue seems to have been solved.
